[package]
name = "tp-exec"
version = "0.1.0"
authors = ["Christine Dodrill <xe@tailscale.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
envy = "0.4"

tailpam = { path = "../../crates/tailpam" }