name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libpam0g-dev
        cargo install cargo-deb
    - name: Build
      run: |
        cargo deb -p pam_tailscale
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: pam_tailscale_0.1.0_amd64.deb
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/debian/pam_tailscale_0.1.0_amd64.deb
        if-no-files-found: error
        # The desired behavior if no files are found using the provided path.
        retention-days: 90
